import { Colors } from '../../../../constants/theme';

const colors = {
  primaryColor: Colors.vfRed,
  primaryColorRGBA: Colors.vfRedRGBA,
  secondryColor: Colors.red,
  tintColor: Colors.white,
  tintColorRGBA: Colors.whiteRGBA,
  accentColor: Colors.black,
  accentColorRGBA: Colors.blackRGBA,
  fixedColor: Colors.blackTwo,
  activeColor: Colors.ocean,
  activeColorTwo: Colors.white,
  activeColorThree: Colors.ocean,
  activeColorFour: Colors.ocean,
  activeColorRGBA: Colors.oceanRGBA,
  activeTabColor: Colors.secondary7,
  activeTabColorThree: Colors.vfRed,
  inActiveColor: Colors.whiteSmoke,
  inActiveColorTwo: Colors.brownGrey,
  inActiveColorThree: Colors.smoothGrey,
  inActiveColorFour: Colors.brownGrey,
  radioButtonBorderColor: Colors.veryLightPink,
  headerColor: Colors.mono6,
  textColor: Colors.black,
  textColorTwo: Colors.mono6,
  textColorThree: Colors.thinDark,
  textColorFive: Colors.charcoalGreyTwo,
  textColorSix: Colors.charcoalGreyTwo,
  textColorSeven: Colors.charcoalGrey,
  textColorEight: Colors.light_black,
  textColorNine: Colors.smoothGreyTwo,
  textColorTen: Colors.black,
  optionBorderColor: Colors.brownGrey,
  borderColor: Colors.brownGrey,
  borderColorTwo: Colors.veryLightPink,
  borderColorThree: Colors.mono3,
  borderColorThreeRGBA: Colors.veryLightPinkTwoRGBA,
  borderColorFour: Colors.veryLightPinkTwo,
  borderColorFive: Colors.brownGrey,
  borderColorSix: Colors.white_two,
  borderColorSeven: Colors.dark_grey,
  borderColorEight: Colors.veryLightPinkTwo,
  borderColorNine: Colors.mono3,
  horizontalLineColor: Colors.mono3,
  errorColor: Colors.error,
  overlayColor: Colors.overlay,
  backgroundColor: Colors.background,
  backgroundColorTwo: Colors.whisper,
  backgroundColorThree: Colors.offWhite,
  backgroundColorFour: Colors.white,
  backgroundColorFive: Colors.whiteSmoke,
  backgroundColorSix: Colors.white,
  backgroundColorSeven: Colors.mono2,
  fillColor: Colors.mono3,
  fillColorTwo: Colors.mono3,
  loadingTextColor: Colors.vfRed,
  cardBackgroundColor: Colors.cardBackground,
  cardBackgroundColorTwo: Colors.veryLightPink,
  transparentColor: Colors.transparent,
  windowTintColor: Colors.windowTint,
  shadowColor: Colors.shadow,
  shadowColorTwo: Colors.lightShadow,
  toggleColor: Colors.whiteSmoke,
  activeToggleRGBA: Colors.ocean2RGBA,
  headerTitleColor: Colors.dark_grey,
  inactiveTrayItemColor: Colors.dark_grey,
  trayHandleButton: Colors.brownGreyTwo,
  showMoreColor: Colors.vfRed,
  cardHeaderTitleColor: Colors.veryLightGreyTwo,
  sectionHeaderTextColor: Colors.blackTwo,
  sectionItemTextColor: Colors.mono6,
  toggleBackgroundColor: Colors.brownGrey,
  inactiveToggleRGBA: Colors.brownGreyRGBA,
  lightTextColor: Colors.black,
  nonCompletedCircle: Colors.brownGrey,
  errorCardColor: Colors.activeGrey,
  tryAgainColor: Colors.secondary7,
  shimmerBorder: Colors.lightGrayTwo,
  shimmerEdgesColor: Colors.whisper,
  shimmerCenterColor: Colors.mono3,
  statusBarColor: Colors.whiteSmoke,
  toggleBorderColor: Colors.transparent,
  hyperlink: Colors.blackTwo,
  hyperlinkTwo: Colors.white,
  hyperlinkThree: Colors.dark_grey,
  hyperlinkFour: Colors.smoothGrey,
  hyperlinkFive: Colors.vfRed,
  hyperlinkSix: Colors.secondary7,
  radioButton: Colors.blue_two,
  tutorialBackgroundColor: Colors.veryLightPinkTwo,
  divider: Colors.white_two,
  dividerTwo: Colors.white_two,
  dividerThree: Colors.veryLightPink,
  subtitle: Colors.mono5,
  usagePercentage: Colors.dark_grey,
  activeTabColorTwo: Colors.vfRed,
  indicatorBackground: Colors.white_two,
  inActiveDot: Colors.veryLightPink,
  errorMessageColor: Colors.dark_grey,
  subErrorMessageColor: Colors.dark_grey,
  rememberMeText: Colors.dark_grey,
  inputIconColor: Colors.vfRed,
  quickActionBackground: Colors.background,
  textColorFour: Colors.true_green,
  boldTextColor: Colors.thinDark,
  cardBackgroundColorThree: Colors.white,
  cardBackgroundColorFour: Colors.white,
  seeBillColor: Colors.vfRed,
  filterBarItemColor: Colors.veryLightPinkTwo,
  percentageIndicator: Colors.vfRed,
  usageTitle: Colors.mono5,
  usageSubTitle: Colors.secondary7,
  editText: Colors.secondary7,
  orderSummaryTitle: Colors.mono5,
  activeStep: Colors.vfRed,
  inactiveSeparator: Colors.brownGrey,
  quickActionGradientColors: {
    primary: [Colors.vfRed, Colors.red, Colors.darkRed],
    secondary: [Colors.white, Colors.white],
  },
  picker: {
    top: Colors.pearlTwo,
    bottom: Colors.pearl,
    activeItem: Colors.veryLightSilver,
    dropdownActiveItem: Colors.white_two,
    chevronInActive: Colors.veryLightGreyThree,
    chevronActive: Colors.babyBlue3,
    doneText: Colors.babyBlue3,
    placeholder: Colors.dark_grey,
    itemColor: Colors.black,
  },
  VFDivider: {
    primary: Colors.mono3,
    secondary: Colors.whiteRGBA(0.32),
    tertiary: Colors.mono3,
  },
  buttons: {
    primary: {
      default: Colors.vfRed,
      active: Colors.activeRed,
      borderColor: Colors.vfRed,
    },
    primaryWhite: {
      default: Colors.white,
      active: Colors.activeGrey,
    },
    secondaryBlack: {
      default: Colors.mono6,
      active: Colors.lightGrayTwo,
    },
    secondary: {
      default: Colors.white,
      active: Colors.dark_grey_3,
      borderColor: Colors.dark_grey,
    },
    tertiary: {
      default: Colors.light_grey,
      active: Colors.blackTwo,
    },
    quaternary: {
      default: Colors.white,
      active: Colors.activeGrey,
      borderColor: Colors.brownGrey,
    },
    quinary: {
      default: Colors.transparent,
      active: Colors.transparent,
      borderColor: Colors.white,
    },
    tray: {
      default: Colors.vfRed,
      active: Colors.blackTwo,
    },
    option: {
      default: Colors.background,
      active: Colors.offWhite,
    },
    default: {
      default: Colors.smoothGrey,
      active: Colors.blackTwo,
    },
    success: {
      default: Colors.success,
      active: Colors.true_green,
    },
    disabled: Colors.lightGrey,
    disabledTwo: Colors.veryLightPink,
    disabledThree: Colors.veryLightPink,
  },
  textButtons: {
    primary: {
      default: Colors.white,
    },
    primaryWhite: {
      default: Colors.blackTwo,
    },
    secondaryBlack: {
      default: Colors.white,
    },
    secondary: {
      default: Colors.dark_grey,
    },
    tertiary: {
      default: Colors.white,
    },
    quaternary: {
      default: Colors.blackTwo,
    },
    quinary: {
      default: Colors.white,
    },
    disabled: Colors.white,
  },
  textInput: {
    default: {
      baseColor: Colors.light_grey,
      tintColor: Colors.ocean,
      selectionColor: Colors.warm_grey_two,
      baseColorTwo: Colors.dark_grey,
      labelTextColor: Colors.light_grey,
      helperTextColor: Colors.white,
    },
    error: {
      baseColor: Colors.vfRed,
      tintColor: Colors.vfRed,
      helperText: Colors.vfRed,
      selectionColor: Colors.warm_grey_two,
    },
    errorColor: {
      baseColor: Colors.secondary7,
      tintColor: Colors.secondary7,
      helperText: Colors.secondary7,
      selectionColor: Colors.warm_grey_two,
    },
  },
  text: {
    primary: Colors.dark_grey,
    primaryWhite: Colors.white,
    secondary: Colors.white,
    tertiary: Colors.vfRed,
    textWithIcon: Colors.secondary7,
    text: Colors.black,
    primaryGrey: Colors.warm_grey,
  },
  checkBox: {
    background: Colors.ocean,
    mark: Colors.white,
    border: Colors.brownGrey,
  },
  countDown: {
    disabled: Colors.dark_grey,
    enabled: Colors.secondary7,
  },
  backgroundGradientColors: [Colors.vfRed, Colors.darkRedTwo],
  background: {
    primary: [Colors.pearlTwo, Colors.whiteSmoke],
    secondary: [Colors.vfRed, Colors.darkRedTwo],
    tertiary: [Colors.vfRed, Colors.darkRedTwo],
  },
  badge: {
    positive: Colors.success,
    neutral: Colors.dark_orange,
    critical: Colors.vfRed,
    processing: Colors.warm_grey_two,
  },
  linearGradient: {
    //same like primary but separated into 2 parts
    primary1: [Colors.pearlTwo, Colors.silver],
    primary2: [Colors.silver, Colors.whiteSmoke],
  },
  usageItem: {
    cardStatus: Colors.secondary5,
    values: Colors.vfRed,
    iconBackground: Colors.mono3,
  },
};

export default colors;
